site_name: Undefined OS 文档
site_url: https://undefined-os.github.io/doc
theme:
  name: material

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format     